[theme]
base = "light"
primaryColor = "#0D1F4B"            # navy for primary action buttons
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0d1f4b"
font = "sans serif"

[client]
# Hide verbose error styling banners that can color widgets red:
showErrorDetails = false

[browser]
gatherUsageStats = false 