[theme]
base = "light"
primaryColor = "#2563eb"            # brand blue for selection
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0d1f4b"
font = "sans serif"

[client]
# CRITICAL: Hide verbose error styling banners that can color widgets red
# This prevents background exceptions from injecting red borders and backgrounds into the UI
# When combined with CSS overrides in assets/css/theme.css, this ensures consistent theming
# DO NOT REMOVE - this is essential for production deployment
showErrorDetails = false

[browser]
gatherUsageStats = false
