[theme]
base = "light"
primaryColor = "#2563eb"            # brand blue for selection
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0d1f4b"
font = "sans serif"

[client]
# Hide verbose error styling banners that can color widgets red:
showErrorDetails = false

[browser]
gatherUsageStats = false
